# Generated by Django 4.1.5 on 2023-01-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_woner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='woner',
            new_name='owner',
        ),
    ]
